// <auto-generated />
using System;
using MAD.DataWarehouse.BIM360.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAD.DataWarehouse.BIM360.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220907213502_UpdateTable_FolderItem_Tip")]
    partial class UpdateTable_FolderItem_Tip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MAD.DataWarehouse.BIM360.Api.Accounts.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessUnitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JobNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastSignIn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StateOrProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("MAD.DataWarehouse.BIM360.Api.Data.FolderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "ProjectId");

                    b.ToTable("FolderItem");
                });

            modelBuilder.Entity("MAD.DataWarehouse.BIM360.Api.Project.Hub", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hub");
                });

            modelBuilder.Entity("MAD.DataWarehouse.BIM360.Api.Data.FolderItem", b =>
                {
                    b.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.FolderItemAttribute", "Attributes", b1 =>
                        {
                            b1.Property<string>("FolderItemId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("FolderItemProjectId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTimeOffset>("CreateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("CreateUserId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CreateUserName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Hidden")
                                .HasColumnType("bit");

                            b1.Property<DateTimeOffset>("LastModifiedTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset>("LastModifiedTimeRollup")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("LastModifiedUserId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastModifiedUserName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("ObjectCount")
                                .HasColumnType("bigint");

                            b1.HasKey("FolderItemId", "FolderItemProjectId");

                            b1.ToTable("FolderItem");

                            b1.WithOwner()
                                .HasForeignKey("FolderItemId", "FolderItemProjectId");

                            b1.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.FolderItemAttributeExtension", "Extension", b2 =>
                                {
                                    b2.Property<string>("FolderItemAttributeFolderItemId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("FolderItemAttributeFolderItemProjectId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Type")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Version")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("FolderItemAttributeFolderItemId", "FolderItemAttributeFolderItemProjectId");

                                    b2.ToTable("FolderItem");

                                    b2.WithOwner()
                                        .HasForeignKey("FolderItemAttributeFolderItemId", "FolderItemAttributeFolderItemProjectId");

                                    b2.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.FolderItemAttributeExtensionData", "Data", b3 =>
                                        {
                                            b3.Property<string>("FolderItemAttributeExtensionFolderItemAttributeFolderItemId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("FolderItemAttributeExtensionFolderItemAttributeFolderItemProjectId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("Actions")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("AllowedTypes")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("NamingStandardIds")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("VisibleTypes")
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("FolderItemAttributeExtensionFolderItemAttributeFolderItemId", "FolderItemAttributeExtensionFolderItemAttributeFolderItemProjectId");

                                            b3.ToTable("FolderItem");

                                            b3.WithOwner()
                                                .HasForeignKey("FolderItemAttributeExtensionFolderItemAttributeFolderItemId", "FolderItemAttributeExtensionFolderItemAttributeFolderItemProjectId");
                                        });

                                    b2.Navigation("Data");
                                });

                            b1.Navigation("Extension")
                                .IsRequired();
                        });

                    b.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.FolderItemRelationships", "Relationships", b1 =>
                        {
                            b1.Property<string>("FolderItemId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("FolderItemProjectId")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("FolderItemId", "FolderItemProjectId");

                            b1.ToTable("FolderItem");

                            b1.WithOwner()
                                .HasForeignKey("FolderItemId", "FolderItemProjectId");

                            b1.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.RelationshipContainer", "Parent", b2 =>
                                {
                                    b2.Property<string>("FolderItemRelationshipsFolderItemId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("FolderItemRelationshipsFolderItemProjectId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.HasKey("FolderItemRelationshipsFolderItemId", "FolderItemRelationshipsFolderItemProjectId");

                                    b2.ToTable("FolderItem");

                                    b2.WithOwner()
                                        .HasForeignKey("FolderItemRelationshipsFolderItemId", "FolderItemRelationshipsFolderItemProjectId");

                                    b2.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.RelationshipContainerData", "Data", b3 =>
                                        {
                                            b3.Property<string>("RelationshipContainerFolderItemRelationshipsFolderItemId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("RelationshipContainerFolderItemRelationshipsFolderItemProjectId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("Id")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("Type")
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("RelationshipContainerFolderItemRelationshipsFolderItemId", "RelationshipContainerFolderItemRelationshipsFolderItemProjectId");

                                            b3.HasIndex("Id");

                                            b3.ToTable("FolderItem");

                                            b3.WithOwner()
                                                .HasForeignKey("RelationshipContainerFolderItemRelationshipsFolderItemId", "RelationshipContainerFolderItemRelationshipsFolderItemProjectId");
                                        });

                                    b2.Navigation("Data");
                                });

                            b1.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.RelationshipContainer", "Tip", b2 =>
                                {
                                    b2.Property<string>("FolderItemRelationshipsFolderItemId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("FolderItemRelationshipsFolderItemProjectId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.HasKey("FolderItemRelationshipsFolderItemId", "FolderItemRelationshipsFolderItemProjectId");

                                    b2.ToTable("FolderItem");

                                    b2.WithOwner()
                                        .HasForeignKey("FolderItemRelationshipsFolderItemId", "FolderItemRelationshipsFolderItemProjectId");

                                    b2.OwnsOne("MAD.DataWarehouse.BIM360.Api.Data.RelationshipContainerData", "Data", b3 =>
                                        {
                                            b3.Property<string>("RelationshipContainerFolderItemRelationshipsFolderItemId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("RelationshipContainerFolderItemRelationshipsFolderItemProjectId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("Id")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("Type")
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("RelationshipContainerFolderItemRelationshipsFolderItemId", "RelationshipContainerFolderItemRelationshipsFolderItemProjectId");

                                            b3.HasIndex("Id");

                                            b3.ToTable("FolderItem");

                                            b3.WithOwner()
                                                .HasForeignKey("RelationshipContainerFolderItemRelationshipsFolderItemId", "RelationshipContainerFolderItemRelationshipsFolderItemProjectId");
                                        });

                                    b2.Navigation("Data");
                                });

                            b1.Navigation("Parent")
                                .IsRequired();

                            b1.Navigation("Tip")
                                .IsRequired();
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Relationships")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
